__title__ = "fsf"
__description__ = "Manage accelerator sequences."
__url__ = "https://gitlab.cern.ch/fcarlier/fsf"
__version__ = "0.0.0"
__author__ = "fcarlier"
__author_email__ = "fcarlier@cern.ch"
__license__ = "MIT"
