base_types = { 
              'Marker'          : 'marker'         ,  
              'Drift'           : 'drift'          ,  
              'Collimator'      : 'collimator'     ,  
              'Monitor'         : 'monitor'        ,  
              'Placeholder'     : 'placeholder'    ,  
              'Instrument'      : 'instrument'     ,  
              'SectorBend'      : 'sbend'          ,  
              'RectangularBend' : 'rbend'          ,     
              'DipoleEdge'      : 'dipedge'        ,  
              'Solenoid'        : 'solenoid'       ,  
              'ThinMultipole'   : 'multipole'      ,  
              'Quadrupole'      : 'quadrupole'     ,  
              'Sextupole'       : 'sextupole'      ,  
              'Octupole'        : 'octupole'       ,  
              'RFCavity'        : 'rfcavity'       ,  
              'HKicker'         : 'hkicker'        ,  
              'VKicker'         : 'vkicker'        ,  
              'TKicker'         : 'tkicker'        ,  
              'ThinMultipole'   : 'thinmultipole'  ,  
              'ThinSolenoid'    : 'thinsolenoid'   ,  
              'ThinRFMultipole' : 'thinrfmultipole', 
              }
